---
# This role installs httpd

- name: Install http
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

# - name: Configure SELinux to allow httpd to connect to remote database
#   seboolean:
#     name: httpd_can_network_connect_db
#     state: true
#     persistent: yes
- name: Check if Apache is accessible
  uri:
    url: http://localhost
    method: GET
    status_code: 200
